name: nap_env
channels:
  - pytorch
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - alsa-lib=1.2.7.2
  - attr=2.5.1
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - biopython=1.84
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.32.3
  - ca-certificates=2024.8.30
  - cairo=1.16.0
  - certifi=2024.8.30
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - cmake=3.26.3
  - deprecated=1.2.14
  - expat=2.6.2
  - ffmpeg=4.3
  - filelock=3.15.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - gawk=5.3.0
  - gcc_impl_linux-64=14.1.0
  - gcc_linux-64=14.1.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.6.13
  - graphite2=1.3.13
  - gstreamer-orc=0.4.39
  - gxx_impl_linux-64=14.1.0
  - gxx_linux-64=14.1.0
  - h2=4.1.0
  - harfbuzz=5.3.0
  - hpack=4.0.0
  - htslib=1.20
  - hyperframe=6.0.1
  - icu=70.1
  - idna=3.7
  - igv=2.17.4
  - intel-openmp=2022.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - k8=0.2.5
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libcap=2.66
  - libcblas=3.9.0
  - libcups=2.3.3
  - libcurl=8.8.0
  - libdeflate=1.20
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-devel_linux-64=14.1.0
  - libgcc-ng=14.1.0
  - libgcrypt=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.2
  - libgomp=14.1.0
  - libgpg-error=1.50
  - libiconv=1.17
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libsanitizer=14.1.0
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-devel_linux-64=14.1.0
  - libstdcxx-ng=14.1.0
  - libsystemd0=252
  - libtiff=4.2.0
  - libuuid=2.38.1
  - libuv=1.48.0
  - libwebp-base=1.4.0
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - mafft=7.525
  - markupsafe=2.1.5
  - miniasm=0.3
  - minimap2=2.28
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - nanofilt=2.8.0
  - nanoget=1.19.3
  - nanomath=1.4.0
  - ncurses=6.5
  - nettle=3.6
  - networkx=3.3
  - numpy=1.26.4
  - openh264=2.1.1
  - openjdk=17.0.3
  - openjpeg=2.4.0
  - openssl=3.3.1
  - pandas=2.2.2
  - pcre2=10.43
  - perl=5.32.1
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.2
  - pthread-stubs=0.4
  - pycparser=2.22
  - pysam=0.22.1
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytorch=2.4.0
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - rhash=1.4.3
  - samtools=1.20
  - seqtk=1.4
  - setuptools=71.0.4
  - shasta=0.12.0
  - six=1.16.0
  - smartdenovo=1.0.0
  - spades=4.0.0
  - sympy=1.13.2
  - sysroot_linux-64=2.17
  - tk=8.6.13
  - torchaudio=2.4.0
  - torchvision=0.19.0
  - typing_extensions=4.12.2
  - tzdata=2024a
  - urllib3=2.2.2
  - vsearch=2.28.1
  - wheel=0.43.0
  - wrapt=1.16.0
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
