name: nap_env
dependencies:
  - python=3.10
  - numpy
  - pandas=2.2.2
  - pysam
  - biopython
  - tqdm
  - pip
  - pip:
    - futures
    - regex
  - conda-forge::minimap2  # Use the conda-forge channel for specific packages
  - conda-forge::samtools
  - conda-forge::blast
  - conda-forge::vsearch
  - conda-forge::NanoFilt
