name: nap_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas=2.2.2
  - biopython
  - tqdm
  - pysam
  - minimap2
  - samtools
  - blast
  - vsearch
  - nanofilt
  - pip
  - pip:
    - futures
    - regex
